name: Generate Snake Game

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3.2.0
